### ISSUE TITLE
Any idea if this will support Pine64?

### ISSUE THREAD

**Issue by hortinstein** [glevand/coreos--manifest#1]
![http://pine64.com/](http://pine64.com/) is a 15 dollar quad core linux pc that runs on Arm64 architecture

**Comment by glevand** [comment]
Please see my comments on the coreos-dev mailing list about the raspberry pi 3: https://groups.google.com/d/msg/coreos-dev/TvlWjJOEfDw/XLvCbX-1KQAJ

If you just want to run CoreOS on arm64, the easiest way is to get a Hikey board: http://www.lenovator.com/product/90.html

Closing this.  Please post to the [ML](https://groups.google.com/forum/#!forum/coreos-dev) to follow up.
